// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdTabHome 30000 
#define cmdTabHome_LabelTitle_RESID 60001
#define cmdGroupClipboard 30005 
#define cmdGroupClipboard_LabelTitle_RESID 60002
#define cmdPaste 30009 
#define cmdPaste_LabelTitle_RESID 60003
#define cmdPaste_TooltipTitle_RESID 60004
#define cmdPaste_TooltipDescription_RESID 60005
#define cmdPaste_LargeImages_RESID 4000
#define cmdCut 30010 
#define cmdCut_LabelTitle_RESID 60006
#define cmdCut_TooltipTitle_RESID 60007
#define cmdCut_TooltipDescription_RESID 60008
#define cmdCut_SmallImages_RESID 60009
#define cmdCopy 30011 
#define cmdCopy_LabelTitle_RESID 60010
#define cmdCopy_TooltipTitle_RESID 60011
#define cmdCopy_TooltipDescription_RESID 60012
#define cmdCopy_SmallImages_RESID 60013
#define cmdUndo 30015 
#define cmdUndo_LabelTitle_RESID 2020
#define cmdUndo_TooltipTitle_RESID 60014
#define cmdUndo_TooltipDescription_RESID 60015
#define cmdUndo_SmallImages_RESID 60016
#define IDC_FILEMENU 2 
#define IDC_MRULIST 30016 
#define IDC_QAT 3 
#define cmdNew 0xE100 
#define cmdNew_LabelTitle_RESID 2021
#define cmdNew_Keytip_RESID 60017
#define cmdNew_TooltipTitle_RESID 60018
#define cmdNew_TooltipDescription_RESID 60019
#define cmdNew_LargeImages_RESID 4016
#define IDC_OPENFILEMORE 20500 
#define cmdOpenFile 0xE101 
#define cmdOpenFile_LabelTitle_RESID 2022
#define cmdOpenFile_LabelDescription_RESID 2023
#define cmdOpenFile_Keytip_RESID 60020
#define cmdOpenFile_TooltipTitle_RESID 60021
#define cmdOpenFile_TooltipDescription_RESID 60022
#define cmdOpenFile_LargeImages_RESID 4017
#define cmdOpenFreeMind 32774 
#define cmdOpenFreeMind_LabelTitle_RESID 2024
#define cmdOpenFreeMind_LabelDescription_RESID 2025
#define cmdOpenFreeMind_LargeImages_RESID 4018
#define cmdSave 0xE103 
#define cmdSave_LabelTitle_RESID 2026
#define cmdSave_Keytip_RESID 60023
#define cmdSave_TooltipTitle_RESID 60024
#define cmdSave_TooltipDescription_RESID 60025
#define cmdSave_LargeImages_RESID 4019
#define cmdSaveAs 0xE104 
#define cmdSaveAs_LabelTitle_RESID 2027
#define cmdSaveAs_TooltipDescription_RESID 60026
#define cmdSaveAs_LargeImages_RESID 4020
#define IDC_PRINTMORE 20501 
#define cmdPrint 57607 
#define cmdPrint_LabelTitle_RESID 2033
#define cmdPrint_LabelDescription_RESID 2028
#define cmdPrint_LargeImages_RESID 4021
#define cmdPrintSetup 57606 
#define cmdPrintSetup_LabelTitle_RESID 2029
#define cmdPrintSetup_LabelDescription_RESID 2030
#define cmdPrintSetup_LargeImages_RESID 4022
#define cmdVersionInfo 20502 
#define cmdVersionInfo_LabelTitle_RESID 211
#define cmdVersionInfo_LargeImages_RESID 4024
#define cmdExit 0xE102 
#define cmdExit_LabelTitle_RESID 2031
#define cmdExit_Keytip_RESID 60027
#define cmdExit_TooltipDescription_RESID 60028
#define cmdExit_LargeImages_RESID 60029
#define cmdGroupBasicOperationGroup 30006 
#define cmdGroupBasicOperationGroup_LabelTitle_RESID 60030
#define IDC_CMD_CONTEXTMAP1 4  /* the Context Map for Context 1 */ 
#define cmdEditNode 31001 
#define cmdEditNode_LabelTitle_RESID 3031
#define cmdEditNode_TooltipTitle_RESID 60031
#define cmdEditNode_TooltipDescription_RESID 60032
#define cmdEditNode_LargeImages_RESID 60033
#define cmdDeleteNode 31002 
#define cmdDeleteNode_LabelTitle_RESID 3032
#define cmdDeleteNode_TooltipTitle_RESID 60034
#define cmdDeleteNode_TooltipDescription_RESID 60035
#define cmdCreateChildNode 31003 
#define cmdCreateChildNode_LabelTitle_RESID 3033
#define cmdCreateChildNode_TooltipTitle_RESID 60036
#define cmdCreateChildNode_TooltipDescription_RESID 60037
#define cmdCreateChildNode_LargeImages_RESID 60038
#define cmdCreateLink 5 
#define cmdCreateLink_LabelTitle_RESID 60039
#define cmdCreateLink_TooltipTitle_RESID 60040
#define cmdCreateLink_TooltipDescription_RESID 60041
#define cmdCreateLink_LargeImages_RESID 60042
#define cmdDeleteLink 6 
#define cmdDeleteLink_LabelTitle_RESID 60043
#define cmdDeleteLink_TooltipTitle_RESID 60044
#define cmdDeleteLink_TooltipDescription_RESID 60045
#define cmdExpandNodes 7 
#define cmdExpandNodes_LabelTitle_RESID 209
#define cmdCollapseNodes 8 
#define cmdCollapseNodes_LabelTitle_RESID 210
#define cmdFontControlGroup 9 
#define cmdFontControlGroup_LabelTitle_RESID 205
#define cmdFontControl 10 
#define cmdFontControl_Keytip_RESID 206
#define cmdBackgroundColorGroup 11 
#define cmdBackgroundColorGroup_LabelTitle_RESID 207
#define cmdBackgroundColor 12 
#define cmdBackgroundColor_LabelTitle_RESID 208
#define cmdBackgroundColor_LargeImages_RESID 60046
#define cmdNodeShape 13 
#define cmdNodeShape_LabelTitle_RESID 60047
#define cmdLineAttributeGroup 14 
#define cmdLineAttributeGroup_LabelTitle_RESID 60048
#define cmdLineColor 15 
#define cmdLineColor_LabelTitle_RESID 60049
#define cmdLineWidth 16 
#define cmdLineWidth_LabelTitle_RESID 60050
#define cmdLineEdgeStyle 17 
#define cmdLineEdgeStyle_LabelTitle_RESID 60051
#define cmdLineStyle 18 
#define cmdLineStyle_LabelTitle_RESID 60052
